name: testing-ga

on: push

jobs:
  getversions:
    runs-on: ubuntu-latest
    steps:
      - name: GetGitVersion
        run: git --version

      - name: GetNodeVersion
        run: node --version

      - name: GetJavaVersion
        run: java -version

  copyfiles:
    runs-on: ubuntu-latest
    steps:
      - name: CreateDirectory
        run: mkdir myfiles

      - name: GetFiles
        run: wget https://downloads.apache.org/aries/blueprint-maven-plugin-1.1.0-source-release.zip

      - name: MoveAndUnzip
        run: |
          mv blueprint-maven-plugin-1.1.0-source-release.zip myfiles/
          cd myfiles
          unzip blueprint-maven-plugin-1.1.0-source-release.zip

